-- ============================================================================
-- Estudio Cavallo — Seed data
-- Migrated from the previous localStorage-backed app (snapshot dated 2026-08-03).
-- Run this AFTER schema.sql. Contains real client names and phone numbers —
-- treat as sensitive, do not commit to a public repository.
-- ============================================================================

-- Cars
insert into cars (case_date, client, phone, financed, plate_number, registry_number, make_model, plate_number_2, registry_number_2, make_model_2, case_type, assignees, notarization_assignees, lien_status, seizure_status, debt_status, sucive_certificate_status, required_plates_status, document_drafted_status, paid_status, status, registry_filing_number, pin, reminder_date, priority, notes, completed_at, ready_to_schedule) values
  ('2026-08-03', 'DIEGO NUÑEZ', NULL, false, 'SCQ3872', '1018655', 'PEUGEOT 307', NULL, NULL, NULL, 'Sale', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Returned from Registry', NULL, NULL, NULL, NULL, 'PERMUTA 2008', NULL, false),
  ('2026-08-03', 'DIEGO NUÑEZ', NULL, false, 'ERB5875', '903232102', 'PEUGEOT 2008', NULL, NULL, NULL, 'Sale', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Ready to Sign', NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('2026-08-03', 'CALIFANO', NULL, false, 'SAU2972', '438308', 'DAIHATSU APPLAUSE', NULL, NULL, NULL, 'Sale', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Ready to Notarize', NULL, NULL, NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'MANU', NULL, false, 'KDB2648', '901648294', 'VW AMAROK', NULL, NULL, NULL, 'Power of Attorney', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Pending', NULL, NULL, NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'MANU', NULL, false, 'IAG8903', '902952964', 'VW AMAROK', NULL, NULL, NULL, 'Sale', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Pending', NULL, NULL, NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'BALARINI', NULL, false, 'MAK1262', '903677095', 'BYD YUAN PLUS', NULL, NULL, NULL, 'Power of Attorney', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Pending', NULL, NULL, NULL, NULL, 'FALTAN DATOS DE SA', NULL, false),
  ('2026-08-03', 'BALARINI', NULL, false, 'BED4388', '903864053', 'BYD SEAGULL', NULL, NULL, NULL, 'Power of Attorney', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Completed', NULL, NULL, NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'BALARINI', NULL, false, 'SCT5836', '903468616', 'VW NIVUS', NULL, NULL, NULL, 'Power of Attorney', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Ready to Sign', NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('2026-08-03', 'TOMAS', NULL, false, NULL, NULL, 'NISSAN KICKS', NULL, NULL, NULL, 'Power of Attorney', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Pending', NULL, NULL, NULL, NULL, 'FALTA CONTROL PERSONERIA JURIDICA', NULL, false),
  ('2026-08-03', 'MARIO SAAVEDRA', NULL, false, NULL, NULL, 'SUZUKI SWIFT', NULL, NULL, NULL, 'Power of Attorney', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Pending', NULL, NULL, NULL, NULL, 'FALTA DIVORCIO', NULL, false),
  ('2026-08-03', 'MANU', NULL, false, NULL, NULL, 'SURAN POR KWID', NULL, NULL, NULL, 'Sale', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Ready to Sign', NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('2026-08-03', 'DIEGO NUÑEZ', NULL, false, NULL, NULL, 'ALTO POR ALTO', NULL, NULL, NULL, 'Sale', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Ready to Sign', NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('2026-08-03', 'RAUL', '098048443', false, 'SCV6800', '903451479', 'VW NIVUS', NULL, NULL, NULL, 'Sale', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Pending', NULL, NULL, NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'RAUL', NULL, false, 'BEC3224', '903214979', 'VW GOLF', NULL, NULL, NULL, 'Sub-power of Attorney', ARRAY['Alex', 'Belén']::text[], '{}', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'not_requested', 'Pending', NULL, NULL, NULL, NULL, NULL, NULL, false);

-- Documents
insert into documents (case_date, client, phone, document_type, reference, assignees, drafted, reviewed, delivered, paid, status, probate_status, power_of_attorney_status, vehicle, registry_number, scan_status, reconstruction_status, documentation_requested, sas_status, next_action_owner, reminder_date, priority, notes, completed_at) values
  ('2026-08-03', 'EDUARDO CARTA DE PAGO', NULL, 'Estate Probate', NULL, ARRAY['Alex', 'Belén']::text[], false, false, false, false, 'Pending', 'Gathering Information', 'Gathering Data', NULL, NULL, 'Pending', 'Pending', false, 'Missing Documentation', 'Nicolás', NULL, NULL, NULL, NULL),
  ('2026-08-03', 'ANDRES CALCAGNO', NULL, 'Other', NULL, ARRAY['Alex', 'Belén']::text[], false, false, false, false, 'Pending', 'Gathering Information', 'Gathering Data', NULL, NULL, 'Pending', 'Pending', false, 'Missing Documentation', 'Nicolás', NULL, NULL, 'ANV', NULL),
  ('2026-08-03', 'JUAN CORREA', NULL, 'Estate Probate', NULL, ARRAY['Alex', 'Belén']::text[], false, false, false, false, 'Pending', 'CRA', 'Gathering Data', NULL, NULL, 'Pending', 'Pending', false, 'Missing Documentation', 'Nicolás', NULL, NULL, NULL, NULL),
  ('2026-08-03', 'PIERRE', NULL, 'Estate Probate', NULL, ARRAY['Alex', 'Belén']::text[], false, false, false, false, 'Pending', 'CRA', 'Gathering Data', NULL, NULL, 'Pending', 'Pending', false, 'Missing Documentation', 'Nicolás', NULL, NULL, 'TRAMITE PARA BANCO', NULL),
  ('2026-08-03', 'PIERRE', NULL, 'Estate Probate', NULL, ARRAY['Alex', 'Belén']::text[], false, false, false, false, 'Pending', 'Registration', 'Gathering Data', NULL, NULL, 'Pending', 'Pending', false, 'Missing Documentation', 'Nicolás', NULL, NULL, 'TESTIMONIO PARA COBRO POR BANCO', NULL),
  ('2026-08-03', 'LABARTHE', NULL, 'Estate Probate', NULL, ARRAY['Alex', 'Belén']::text[], false, false, false, false, 'Pending', 'Gathering Information', 'Gathering Data', NULL, NULL, 'Pending', 'Pending', false, 'Missing Documentation', 'Nicolás', NULL, NULL, 'PRESUNTOS HEREDEROS PARA BANCO', NULL),
  ('2026-08-03', 'SANTO MAURO', NULL, 'Estate Probate', NULL, ARRAY['Alex', 'Belén']::text[], false, false, false, false, 'Pending', 'CRA', 'Gathering Data', NULL, NULL, 'Pending', 'Pending', false, 'Missing Documentation', 'Nicolás', NULL, NULL, 'LEVANTAR CRA', NULL),
  ('2026-08-03', 'SANTIAGO HAM', NULL, 'SAS', NULL, ARRAY['Alex', 'Belén']::text[], false, false, false, false, 'In Progress', 'Gathering Information', 'Gathering Data', NULL, NULL, 'Pending', 'Pending', true, 'Missing Documentation', 'Nicolás', NULL, NULL, 'COMPRAVENTA DE ACCIONES', NULL),
  ('2026-08-03', 'SERGIO BURGOS', NULL, 'Notarial Certificate', NULL, ARRAY['Alex', 'Belén']::text[], false, false, false, false, 'Pending', 'Gathering Information', 'Gathering Data', NULL, NULL, 'Pending', 'Pending', false, 'Missing Documentation', 'Nicolás', NULL, NULL, 'NOTARIAL PARA BPS', NULL),
  ('2026-08-03', 'FELIPE HOUNIE', NULL, 'Document Scanning', NULL, ARRAY['Alex', 'Belén']::text[], false, false, false, false, 'Pending', 'Gathering Information', 'Gathering Data', 'SUXUKI CELERIO', '902790408', 'Completed', 'Pending', false, 'Missing Documentation', 'Nicolás', NULL, NULL, NULL, NULL);

-- Properties
insert into properties (case_date, property_type, client, registry_number, assignees, registry_filing_number, pin, buyer_phone, seller_phone, notary_phone, id_cards, titles, survey_plan, property_tax_receipt, school_tax_receipt, cadastral_info, project_plan, personal_status_certificate, property_certificate, business_lien_certificate, first_copy, taxes_paid, offering_certificate, article_358_certificate, colonization_certificate, mining_certificate, registration_status, stage, status, next_action_owner, next_action, reminder_date, priority, notes, completed_at, ready_to_schedule) values
  ('2026-08-03', 'Urban', 'GUILLERMO ROSSEINDORF', 'ESPERANDO SUCESION', ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Preparing Agreement', 'Pending', 'Nicolás', NULL, NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'Urban', 'VERONICA FERNANDEZ 097966095', 'GROU', ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', NULL, NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'Urban', 'MONTSERRAT 092806201', NULL, ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Preparing Agreement', 'Pending', 'Nicolás', NULL, NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'Urban', 'MERELLO', 'CASA PIRIA', ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'ok', 'Sale Deed', 'Pending', 'Nicolás', NULL, '2026-08-03', 'High', NULL, NULL, false),
  ('2026-08-03', 'Urban', 'NATALY BERTINAT Y ERNESTO', 'LA PALOMA', ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', 'ESCRIBANO INSCRIBIENDO SUCESION', NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'Urban', 'HERNAN PEREYRA Y KEVIN LAGUNA', 'EUSKAL', ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', 'ESTUDIO DE DOCUMENTACION', NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'Urban', 'HERNAN PEREYRA', 'BARRIO CEIBO', ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', 'SOLICITAR DOCUMENTACION', NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'Urban', 'MERELLO', 'USS170 PIRIAPOLIS', ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', 'ESTUDIO DE DOCUMENTACION', NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'Urban', 'MERELLO', 'USS110 MONTEVIDEO', ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', NULL, NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'Urban', 'LORELEY', 'COMPRAVENTA JUDICIAL', ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', 'EJECUTAR', NULL, 'Medium', NULL, NULL, false),
  ('2026-08-03', 'Urban', 'MANUEL', 'CHACRA PAYSANDU', ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', 'CONTRIBUCION Y PRIMARIA', NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'Urban', 'CALIFANO', 'JAUREGUIVERRY', ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', 'ESTUDIO DE DOCUMENTACION', NULL, 'Medium', NULL, NULL, false),
  ('2026-08-03', 'Urban', 'GASTON PRADERI', NULL, ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', 'SOLICITAR DOCUMETNACIOIN', NULL, 'Medium', NULL, NULL, false),
  ('2026-08-03', 'Urban', 'LOLO CAZENAVE', NULL, ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', NULL, NULL, 'Medium', NULL, NULL, false),
  ('2026-08-03', 'Urban', 'FELIPE', NULL, ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', NULL, NULL, NULL, NULL, NULL, false),
  ('2026-08-03', 'Urban', 'MARCE COGOY', 'EUSKAL', ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', 'FIRMA CON BANCO', NULL, 'High', NULL, NULL, false),
  ('2026-08-03', 'Urban', 'Bidegain', 'Chacras', ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Preparing Agreement', 'Pending', 'Nicolás', 'Ver documento compraventa e impuestos. Enviarle a Bidegain', NULL, 'High', NULL, NULL, false),
  ('2026-08-03', 'Urban', 'FRANCISCO TURTU', NULL, ARRAY['Dahiana']::text[], NULL, NULL, NULL, NULL, NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'not_requested', 'Agreement Signed', 'Pending', 'Nicolás', 'PEDIR PROYECTO DE CV. PEDIR NOTARIAL NO GASTOS COMUNES. PEDIR SEGURO', NULL, 'High', NULL, NULL, false);

-- Signing appointments
insert into signing_appointments (appointment_date, appointment_time, origin, client, description, notes) values
  ('2026-08-03', '14:00', 'Car', 'AGUSTIN', 'I10', 'VER CERTIFICADOS'),
  ('2026-08-06', '15:30', 'Property', 'MARCE COGOY', NULL, NULL),
  ('2026-08-03', '16:30', 'Car', 'MANU', 'DODGE', 'PERMUTA POR RAM'),
  ('2026-08-03', '12:30', 'Property', 'FELIPE RAVERA', NULL, NULL),
  ('2026-08-03', '16:00', 'Car', 'MANU', 'AMAROK POR AMAROK', NULL),
  ('2026-08-05', '17:30', 'Property', 'CALIFANO', NULL, 'MOSTRAR PROPIEDAD'),
  ('2026-08-03', '17:00', 'Car', 'CALIFANO', 'DAIHATSU APPLAUSE', NULL),
  ('2026-08-03', '16:00', 'Car', 'DIEGO', '2008 POR 307', NULL);

-- Documents ready to schedule
insert into documents_ready_to_schedule (client, description, notes) values
  ('DIEGO NUÑEZ', 'ALTO POR ALTO', NULL),
  ('MANU', 'SURAN POR KWID', NULL),
  ('BALARINI', 'BYD YUAN PLUS', 'FALTAN DATOS DE SA');

-- Properties near signing
insert into properties_near_signing (client, registry_number, missing_items) values
  ('MARCE COGOY', 'EUSKAL', 'AMPLIAR. ACTUALIZ');

